-- return {
--     "mfussenegger/nvim-lint",
--     event = { "BufReadPre", "BufNewFile" }, -- autoload when opening files
--     config = function()
--         local lint = require("lint")
--
--         -- point pylint to your pyenv venv binary
--         lint.linters.pylint.cmd = "/Users/ningyuheng/.pyenv/versions/neovim/bin/pylint"
--
--         -- assign linters by filetype
--         lint.linters_by_ft = {
--             javascript = { "eslint_d" },
--             typescript = { "eslint_d" },
--             javascriptreact = { "eslint_d" },
--             typescriptreact = { "eslint_d" },
--             svelte = { "eslint_d" },
--             python = { "pylint" },
--         }
--
--         -- auto-run lint when entering or saving files
--         local lint_augroup = vim.api.nvim_create_augroup("lint", { clear = true })
--         vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "InsertLeave" }, {
--             group = lint_augroup,
--             callback = function()
--                 lint.try_lint()
--             end,
--         })
--
--         -- manual lint trigger
--         vim.keymap.set("n", "<leader>l", function()
--             lint.try_lint()
--         end, { desc = "Trigger linting for current file" })
--     end,
-- }
